import 'package:flutter/material.dart';
const Color kActiveColor =  Color(0xFF1D1E33);
const Color kInactiveColor =  Color(0xFF111328);
const Color kBottombutton =  Color(0xFFEB1555);
const kLabelTextStyle = TextStyle(fontSize: 18.0, color: Color(0xFF8D8E98));
const kLabelBoldTextStyle = TextStyle(fontWeight: FontWeight.w900, fontSize: 50.0, color: Colors.white);
const kTitleTextStyle = TextStyle(fontWeight: FontWeight.bold, fontSize: 50.0, color: Colors.white);
const kResultTextStyle = TextStyle(fontWeight: FontWeight.bold, fontSize: 22.0, color: Colors.lightGreenAccent);
const kBMIDescTextStyle = TextStyle(fontWeight: FontWeight.bold, fontSize: 22.0, color: Colors.white);
const kBMITextStyle = TextStyle(fontWeight: FontWeight.bold, fontSize: 100.0, color: Colors.white);
int weight = 50;
int age = 25;